# Generated by Django 5.0 on 2023-12-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('fam', models.CharField(max_length=30)),
                ('yosh', models.CharField(max_length=2)),
                ('address', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=100)),
            ],
        ),
    ]
